### ISSUE TITLE
Support connection hand-off from http.Server

### ISSUE THREAD

**Issue by rmg** [alexhultman/node-lws#23]
One of the most useful features of ws and other websocket implementations is the ability to pass them http requests that have already gone through authentication/session checks and have them take over the upgrade handling.

From a quick look at the libwebsocket API it doesn't look like this would easy (if it is even possible). If that ends up being the case then it would probably be worth documenting as a limitation.

**Comment by alexhultman** [comment]
When I started to wrap libwebsockets up I realized there was no way I could shove this into Node.js. It was like an organ transplant gone Macchiarini on me. That problem is now solved and libwebsockets and Node.js shares the same event-loop on the same thread and operates seamlessly.

My point is that, well you get my point.

**Comment by alexhultman** [comment]
I'm not very familiar with Node.js usages, I have barely used it myself. What is the deal with http.Server? Wouldn't the easiest intermediate solution be to instead move over to using the built-in HTTP support in libwebsockets? I mean, I will try to make things as seamless as possible but if something equivalent already exists in libwebsockets I would rather use that.

**Comment by alexhultman** [comment]
But in worst case scenario the socket being opened and "owned" by http.Server is really just a file descriptor which easily could be adopted by libwebsockets. The http.Server just need to drop it without closing it and then we just need to get the FD and poll on it. So in any case it should be possible but I would need some examples and more info.

**Comment by rmg** [comment]
If I remember, I'll try to come up with an example snippet for the usage. In the meantime, the API docs for the method used is at https://github.com/websockets/ws/blob/master/doc/ws.md#serverhandleupgraderequest-socket-upgradehead-callback

**Comment by alexhultman** [comment]
Yes I saw that function, thanks. The problem to solve first of all is how to get a file descriptor from the provided net.Socket. From that point on it should be pretty straight forward I think. But Node.js developers refuse to add this support due to Windows compatibility so I need to investigate how to get some kind of native handle from the net.Socket.

**Comment by alexhultman** [comment]
I think the most immediate solution to this thing is just to move from http.Server and use the built-in HTTP/HTTPS support in libwebsockets. Then we can see how useful further cooperation between http.Server and node-lws would be.

#26 is about implementing the HTTP support and this will be done very soon.

**Comment by alexhultman** [comment]
Yes if you need HTTP and WS support in one server you will need to move from using http.Server to using the HTTP server in libwebsockets. I can see that other websocket implementations rely on the Node.js http.Server but this is not the case with libwebsockets because it is its own HTTP server. So there is no need to clutter things with transactions between the two separate worlds. As long as the HTTP support in node-lws is about the same as the support in http.Server the change should be painless. Then you would get automatically handled upgrades from already established HTTP connections.

If you then need to incorporate the HTTP server in some kind of express or whatever, maybe you should have some kind of getHTTPServer function that returns an object that wraps the libwebsockets HTTP server into a http.Server - I don't know what is needed here but it should be possible to integrate it that way.

**Comment by rmg** [comment]
I think most node developers would find it weird to use a different http server in their app.

Anyways, those are just my thoughts. You made a comment somewhere about being new to node, so I was just trying to help by pointing out an interface that is more node like. :-)

**Comment by LordMajestros** [comment]
@alexhultman I agree with @rmg. One possible issue would be attaching various middlewares to the http server. Middleware is the name for code that does things like set/get cookies, process routes/links, etc and node has a lot of middleware. If the libwebsockets http server supports attaching middleware then no problem otherwise many folks would find it hard to switch.
Also frameworks like socket.io allow regular http authentication before handing over to a websocket server on upgrade restricting access to websocket to authenticated users. This is done using the regular http library. Wether or not libwebsockets supports middleware this authentication may be necessary in some form.

**Comment by alexhultman** [comment]
Okay so I see two solutions:

Either you make this transaction possible by moving the file descriptor but you would also need to move any SSL state along. This moght be possible and then it would work with any other abstractions.

Or you instead try to wrap the libwebsockets HTTP server in the same interface as http.Server and fetch this phony object for use with the abstractions.

**Comment by alexhultman** [comment]
I did a test server in Node.js and I was able to get the file descriptor:

```javascript
const http = require('http');

var srv = http.createServer( (req, res) => {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('this is just a regular http request');
});

srv.on('upgrade', (req, socket, head) => {
  console.log(req);

  console.log('this is where a websocket is made');
  console.log('this is the socket file descriptor: ' + socket._handle.fd);
  socket.end();
});

srv.listen(3000);
console.log('we are listening');
```

```socket._handle.fd``` holds the file descriptor and this makes it very straight forward to adopt this connection. So going from Node.js HTTP to libwebsockets WS should be simple, but doing the HTTPS to WSS transition should require more work.

I need this "socket adoption" feature in libwebsockets anyways to support an external load balancer so this could be a nice first step.

**Comment by alexhultman** [comment]
I did some cleaning in this thread so if comments seem strange, that's why.

So basically this issue is two parts: moving the *socket* into libwebsockets, and moving the *SSL* into libwebsockets. You can get the file descriptor from ```socket._handle.fd``` but if you then create a new uv_poll_t using this fd you get assertion errors since there are two handles polling the same fd (uv_tcp_t from Node.js and uv_poll_t from libwebsockets). It is possible to clone the fd using Unix dup but this would probably not scale very well as it would have two fds per socket.

So intead it might be best to try and port the libuv backend from using uv_poll_t into using uv_tcp_t like Node.js and then just pass this socket into libwebsockets. Then there would only be one handle per socket.

Then the SSL state needs to be moved into libwebsockets, I don't know exactly how but it should be possible.

This seems like an important feature so I will look into this but it might be something that will not land in the first "production ready" version.

**Comment by alexhultman** [comment]
There is now *experimental* connection hand-off for HTTP -> WS. Tested with 1 million connections but Andy is doing a lot of great work in libwebsockets to make things more stable.

**Comment by alexhultman** [comment]
One interesting thing is that the Node.js http.Server 'upgrade' event only handles 18 connections/ms. So this will bottleneck the connection performance down from 99 connections/ms. But I guess no one cares about connection performance.

**Comment by alexhultman** [comment]
I'm closing this as done. Will open a separate bug for SSL transfer.

**Comment by rmg** [comment]
:+1: awesome, thanks for tackling this!

I'm curious how much it would impact this modules benchmark numbers if it used node for the HTTP server and then handed the socket off to libwebsocket. I have a feeling it would drop the connections/second quite a bit, but I may be completely wrong.

**Comment by alexhultman** [comment]
Most (if not all) of this was done by Andy in libwebsockets. I did a benchmark of the upgrade event and it could handle about 18 connections/ms while about 16 /ms with this handoff. So it doesn't really affect connection performance that much (Node itself bottlenecks it pretty hard).
