### ISSUE TITLE
cpu100% and crash after 5m in production!

### ISSUE THREAD

**Issue by renesamaral** [alexhultman/node-lws#36]
HI i saw in oher issues this same issue! After 5-10m of my websockets app running the cpu stops on 100% and the app stop to responds! I try to break the execute of script with control+c but without success, i was only able to stop the process killing them with other session! node v.4.3.1 lws 0.6.1!

I'm only broadcasting messages, looping a array with the sockets socketions that i manage on connect and close events! In my loop i check is socket is true before send the msg!

**Comment by renesamaral** [comment]
What happen if a connection is closed in the time that i'm looping the arraw of connections?

Thats the code that i'm using to looping and broadcast!

server.on('connection', function (socket) {
    console.log('[Connection]');
    users.push(socket);
});

server.on('close', function (socket) {
    users.splice(socket);
    console.log('[Close]');
});

setInterval(function() {
    let m = {};
    m.type = 'logins';
    m.count = users.length;
    let msg = JSON.stringify(m);

    for (let i = 0; i < users.length; i++) {
        server.send(users[i], new Buffer(msg), false);
    }
}, 4000);

**Comment by alexhultman** [comment]
What happens if you try 0.6.0? Also - where do you store the status of the socket? You are not allowed to use the socket in any way after it has been closed.

**Comment by renesamaral** [comment]
the users array! push when connect and splice when disconnect! in the moment that i will send the message, how can i check if the sock is valid? if (socket) ? will try with 0.6 and give you a feedback

**Comment by alexhultman** [comment]
Array.splice takes an integer and you pass it an empty object.

**Comment by alexhultman** [comment]
Server.getFd(socket) will give you an integer

**Comment by ronkorving** [comment]
There's a number of things there asking for improvement.

1. Stop wasting memory by calling `new Buffer(JSON.stringify(m))` before your loop so you don't keep turning strings into buffers for each `server.send` call.
2. Fix your [splice](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) (that's not how it's used, as @alexhultman pointed out).
3. Test again
4. Report back to us :)

**Comment by alexhultman** [comment]
An lws socket is just a pointer, so using it past 'close' is invalid (the memory it points to has been deleted). If you need data (objects, strings, etc) to survive past the 'close' event you need to create that resource in JS-land and attach it to the socket:

[on connection]
server.setUserData(socket, {lwsSocket: socket});

[on close]
server.getUserData(socket).lwsSocket = undefined;

This works because the object `{lwsSocket: socket}` is owned by the GC, so as long as something references it in some way it will not get deleted (as opposed to `socket` which is not owned by the GC). Then you can still read the property `lwsSocket` to check if it is `undefined` or not.

**Comment by renesamaral** [comment]
ty for the answers! I'm using lws to send json messages, so i need to create only one Node buffer and use it with lws? When i need to change my msgs before send, i change de buffer with write method of buffer and then use this same buffer to send the msg? And about broadcast? i'm using the array on connection and close events, like this: users.push(server.getFd(socket)). And then when i need to broadcast, i create a new buffer and do :

for (let i = 0; i < users.length; i++) {
        server.sendPrepared(users[i], preparedBuffer, false);
    }

?

**Comment by alexhultman** [comment]
I can't help you with the actual server writing, only with the documentation of node-lws. You need to make sure that the socket is somehow accessible from some kind of container or part of some kind of 'user' object. Pushing an integer to an array like that would not work since you cannot get the socket back from the fd.

You need to either pre-allocate a large vector of the same length as your ulimit, and then use the fd as an offset in that vector to access some kind of bound resource. Or, you could use the fd as a key in a map. Or you could attach the user object to the socket like described earlier. There are many solutions and I don't know what the best one is for you.

If you plan on sending the same buffer to multiple recipients then you can use prepareBuffer & sendPreprared to minimize internal allocations / copying.

**Comment by renesamaral** [comment]
ok, ty guys!
